### ISSUE TITLE
Names should be displayed differently

### ISSUE THREAD

**Issue by fscholdei** [AkaBlas/akalisten#9]
I am confused by the way the names are currently displayed. I prefer nicknames or first names and the first letter of the last name. Last name comma first name makes no sense at all in the context of our orchestra.
Alternatively, it could be useful to save the user's preferred method in local storage.

**Comment by Bibo-Joshi** [comment]
Sorting by last name was a user request in #5. I'll also have to check which info is available via the polls API - I guess only the display name that is configurable for the user. "First_Name L." Does sound okay for me, though.
Storing user preferences for name sorting will be a big effort, I fear
